# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: facade_logging_service.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'facade_logging_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1c\x66\x61\x63\x61\x64\x65_logging_service.proto\x12\x0b\x66\x61\x63\x61\x64\x65_gRPC\"/\n\x11LogMessageRequest\x12\x0c\n\x04uuid\x18\x01 \x01(\t\x12\x0c\n\x04text\x18\x02 \x01(\t\"$\n\x12LogMessageResponse\x12\x0e\n\x06status\x18\x01 \x01(\x05\"\x14\n\x12GetMessagesRequest\"\'\n\x13GetMessagesResponse\x12\x10\n\x08messages\x18\x01 \x03(\t2\xaa\x01\n\x07Logging\x12M\n\nLogMessage\x12\x1e.facade_gRPC.LogMessageRequest\x1a\x1f.facade_gRPC.LogMessageResponse\x12P\n\x0bGetMessages\x12\x1f.facade_gRPC.GetMessagesRequest\x1a .facade_gRPC.GetMessagesResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'facade_logging_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_LOGMESSAGEREQUEST']._serialized_start=45
  _globals['_LOGMESSAGEREQUEST']._serialized_end=92
  _globals['_LOGMESSAGERESPONSE']._serialized_start=94
  _globals['_LOGMESSAGERESPONSE']._serialized_end=130
  _globals['_GETMESSAGESREQUEST']._serialized_start=132
  _globals['_GETMESSAGESREQUEST']._serialized_end=152
  _globals['_GETMESSAGESRESPONSE']._serialized_start=154
  _globals['_GETMESSAGESRESPONSE']._serialized_end=193
  _globals['_LOGGING']._serialized_start=196
  _globals['_LOGGING']._serialized_end=366
# @@protoc_insertion_point(module_scope)
